# Generated by Django 5.0.3 on 2024-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_item_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
